import java.io.File
import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")
}

val backendBaseUrl = providers.gradleProperty("ticBackendBaseUrl")
    .orElse("https://tic-registration-backend.onrender.com")
    .get()

data class AutoAppVersion(
    val versionCode: Int,
    val versionName: String,
    val generatedAt: String,
)

val appVersionStateFile = file("version.properties")
val appVersionLabelFormatter = DateTimeFormatter.ofPattern("yyyy.MM.dd.HHmmss")
    .withZone(ZoneOffset.UTC)

fun loadStoredAppVersion(file: File): AutoAppVersion {
    if (!file.exists()) {
        return AutoAppVersion(
            versionCode = 1,
            versionName = "0.1.0",
            generatedAt = Instant.EPOCH.toString(),
        )
    }

    val values = file.readLines()
        .mapNotNull { line ->
            val trimmed = line.trim()
            if (trimmed.isBlank() || trimmed.startsWith("#")) {
                return@mapNotNull null
            }

            val separatorIndex = trimmed.indexOf('=')
            if (separatorIndex <= 0) {
                return@mapNotNull null
            }

            val key = trimmed.substring(0, separatorIndex).trim()
            val value = trimmed.substring(separatorIndex + 1).trim()
            key to value
        }
        .toMap()

    return AutoAppVersion(
        versionCode = values["appVersionCode"]?.toIntOrNull()?.coerceAtLeast(1) ?: 1,
        versionName = values["appVersionName"]?.takeIf { it.isNotBlank() } ?: "0.1.0",
        generatedAt = values["generatedAt"]?.takeIf { it.isNotBlank() } ?: Instant.EPOCH.toString(),
    )
}

fun shouldAutoBumpAppVersion(taskNames: List<String>): Boolean {
    if (taskNames.isEmpty()) {
        return false
    }

    return taskNames.any { rawTaskName ->
        val taskName = rawTaskName.substringAfterLast(':').lowercase()
        taskName == "assemble"
            || taskName == "bundle"
            || taskName == "build"
            || (
                taskName.contains("release")
                    && (
                        taskName.contains("assemble")
                            || taskName.contains("bundle")
                            || taskName.contains("package")
                            || taskName.contains("install")
                            || taskName.contains("build")
                    )
                )
    }
}

fun buildNextAutoAppVersion(previous: AutoAppVersion): AutoAppVersion {
    val now = Instant.now()
    val nextVersionCode = maxOf(previous.versionCode + 1, now.epochSecond.toInt())
    return AutoAppVersion(
        versionCode = nextVersionCode,
        versionName = appVersionLabelFormatter.format(now),
        generatedAt = now.toString(),
    )
}

fun persistAutoAppVersion(file: File, version: AutoAppVersion) {
    file.parentFile?.mkdirs()
    file.writeText(
        """
        # Auto-generated by Gradle. Do not edit manually.
        appVersionCode=${version.versionCode}
        appVersionName=${version.versionName}
        generatedAt=${version.generatedAt}
        """.trimIndent() + "\n",
    )
}

val storedAppVersion = loadStoredAppVersion(appVersionStateFile)
val resolvedAppVersion = if (shouldAutoBumpAppVersion(gradle.startParameter.taskNames)) {
    buildNextAutoAppVersion(storedAppVersion)
} else {
    storedAppVersion
}

if (!appVersionStateFile.exists() || resolvedAppVersion != storedAppVersion) {
    persistAutoAppVersion(appVersionStateFile, resolvedAppVersion)
}

val appVersionCode = resolvedAppVersion.versionCode
val appVersionName = resolvedAppVersion.versionName

android {
    namespace = "com.timindonesiacerdas.ticcollect"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.timindonesiacerdas.ticcollect"
        minSdk = 23
        targetSdk = 34
        versionCode = appVersionCode
        versionName = appVersionName
        buildConfigField("String", "BACKEND_BASE_URL", "\"$backendBaseUrl\"")
        buildConfigField("int", "APP_VERSION_CODE", appVersionCode.toString())
        buildConfigField("String", "APP_VERSION_NAME", "\"$appVersionName\"")
        manifestPlaceholders["usesCleartextTraffic"] = "true"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        debug {
            manifestPlaceholders["usesCleartextTraffic"] = "true"
        }
        release {
            isMinifyEnabled = false
            manifestPlaceholders["usesCleartextTraffic"] = "false"
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    val cameraXVersion = "1.4.2"

    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.4")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.4")
    implementation("androidx.activity:activity-compose:1.9.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    implementation(platform("androidx.compose:compose-bom:2024.06.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.navigation:navigation-compose:2.7.7")
    implementation("androidx.exifinterface:exifinterface:1.3.7")
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    implementation("androidx.camera:camera-core:$cameraXVersion")
    implementation("androidx.camera:camera-camera2:$cameraXVersion")
    implementation("androidx.camera:camera-lifecycle:$cameraXVersion")
    implementation("androidx.camera:camera-view:$cameraXVersion")
    ksp("androidx.room:room-compiler:2.6.1")

    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")

    // TODO(stage-2): add Firebase Authentication, Fused Location Provider,
    // WorkManager, Retrofit, OkHttp, and multipart upload support here.
}
